@startuml
class UpdateProfileResponse {
    + Id : string <<get>> <<set>>
    + Success : bool <<get>> <<set>>
    + Message : string <<get>> <<set>>
    + FullName : string <<get>> <<set>>
    + Errors : object <<get>> <<set>>
}
@enduml
